-- Crear base de datos
-- CREATE DATABASE yape_database;

-- Ubicarse en la bd
-- \connect yape_database;

-- Crear esquema yape_1000

CREATE SCHEMA yape_10_000;
CREATE SCHEMA yape_100_000;
CREATE SCHEMA yape_1_000_000;

-- Ubicarse en el esquema
SET search_path TO yape_1_000;
-- SET search_path TO yape_10_000;
-- SET search_path TO yape_100_000;
-- SET search_path TO yape_1_000_000;

-- Creación de tablas

-- Implementación de Checks Básicos solo con atributos de las mismas tablas

-- ===========================
-- Actor y Empresa
-- ===========================
CREATE TABLE Actor_Yape
(
    id_actor INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

CREATE TABLE Persona
(
    id_actor INT PRIMARY KEY,
    dni      VARCHAR(8) UNIQUE NOT NULL,
    correo   VARCHAR(50),
    -- FK
    CONSTRAINT fk_persona_actor
        FOREIGN KEY (id_actor) REFERENCES Actor_Yape (id_actor) ON DELETE CASCADE,
    -- CHECK
    CONSTRAINT chk_persona_dni_formato CHECK ( dni ~ '^[0-9]{8}$' ),
    CONSTRAINT chk_persona_correo_formato CHECK (
        correo ~ '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'
        )
);

CREATE TABLE Empresa
(
    id_actor         INT PRIMARY KEY,
    ruc              VARCHAR(11) UNIQUE NOT NULL,
    razon_social     VARCHAR(100)       NOT NULL,
    rubro_comercial  VARCHAR(100),
    nombre_comercial VARCHAR(100),
    -- FK
    CONSTRAINT fk_empresa_actor
        FOREIGN KEY (id_actor) REFERENCES Actor_Yape (id_actor) ON DELETE CASCADE,
    -- CHECK
    CONSTRAINT chk_empresa_ruc_formato CHECK ( ruc ~ '^[0-9]{11}$' )

);

CREATE TABLE Empresa_Pequeno_Negocio
(
    id_actor         INT PRIMARY KEY,
    dni_duenho       VARCHAR(8),
    correo_contacto  VARCHAR(100),
    celular_contacto VARCHAR(9),
    -- FK
    CONSTRAINT fk_epn_empresa
        FOREIGN KEY (id_actor) REFERENCES Empresa (id_actor) ON DELETE CASCADE,
    -- CHECK
    CONSTRAINT chk_epn_dni_formato CHECK ( dni_duenho ~ '^[0-9]{8}$' ),
    CONSTRAINT chk_epn_correo_formato CHECK (
        correo_contacto ~ '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'
        ),
    CONSTRAINT chk_epn_celular_formato CHECK ( celular_contacto ~ '^[0-9]{9}$' )
);

CREATE TABLE Empresa_Acceso_Empresarial
(
    id_actor INT PRIMARY KEY,
    -- FK
    CONSTRAINT fk_eae_empresa
        FOREIGN KEY (id_actor) REFERENCES Empresa (id_actor) ON DELETE CASCADE
);

CREATE TABLE Empresa_Servicios
(
    id_actor INT PRIMARY KEY,
    -- FK
    CONSTRAINT fk_es_empresa
        FOREIGN KEY (id_actor) REFERENCES Empresa (id_actor) ON DELETE CASCADE
);

-- ===========================
-- Funcionalidad
-- ===========================
CREATE TABLE Funcionalidad
(
    id_funcionalidad INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre           VARCHAR(50) NOT NULL,
    descripcion      VARCHAR(255)
);

-- M:N: ActorYape con Funcionalidad
CREATE TABLE A_Funcionalidad
(
    id_actor         INT NOT NULL,
    id_funcionalidad INT NOT NULL,
    PRIMARY KEY (id_actor, id_funcionalidad),
    -- FK
    CONSTRAINT fk_af_actor FOREIGN KEY (id_actor) REFERENCES Actor_Yape (id_actor) ON DELETE CASCADE,
    CONSTRAINT fk_af_func FOREIGN KEY (id_funcionalidad) REFERENCES Funcionalidad (id_funcionalidad) ON DELETE CASCADE
);

-- ===========================
-- Billetera
-- ===========================
CREATE TABLE Billetera_Yape
(
    id_billetera              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_actor                  INT,         -- NULL permitido para BilleteraOtherPersona
    celular                   VARCHAR(9),
    saldo                     DECIMAL(10, 2)       DEFAULT 0 NOT NULL,
    fecha_creacion            TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    origen_billetera          VARCHAR(50),
    estado                    VARCHAR(20) NOT NULL DEFAULT 'Activo',
    permite_interoperabilidad BOOLEAN     NOT NULL DEFAULT TRUE,
    -- FK
    CONSTRAINT fk_billetera_actor
        FOREIGN KEY (id_actor) REFERENCES Actor_Yape (id_actor) ON DELETE SET NULL,
    -- CHECK
    CONSTRAINT chk_billetera_celular_formato CHECK ( celular ~ '^[0-9]{9}$' ),
    CONSTRAINT chk_billetera_estado
        CHECK (estado IN ('Activo', 'Bloqueado', 'Inactivo')),
    CONSTRAINT chk_billetera_origen CHECK ( origen_billetera IN ('Yape', 'Plin', 'Tunki', 'Agora', 'Tunki', 'Otro', NULL) )
);

CREATE TABLE Billetera_Persona
(
    id_billetera               INT PRIMARY KEY,
    metodo_registro            VARCHAR(30),
    limite_diario              DECIMAL(10, 2) DEFAULT 2000,
    limite_mensual_recaudacion DECIMAL(10, 2) DEFAULT 26750,
    limite_por_operacion       DECIMAL(10, 2) DEFAULT 500,
    bloqueado_fraude           BOOLEAN DEFAULT FALSE,
    nivel_verificacion         VARCHAR(20), -- 'Basico','Avanzado'
    -- FK
    CONSTRAINT fk_bpers_billetera
        FOREIGN KEY (id_billetera) REFERENCES Billetera_Yape (id_billetera) ON DELETE CASCADE,
    -- CHECK
    CONSTRAINT chk_billetera_persona_metodo_registro
        CHECK ( metodo_registro IN ('DNI', 'Cuenta Bancaria', 'Otros Bancos', NULL) ),
    CONSTRAINT chk_billetera_persona_nivel_verificacion
        CHECK ( nivel_verificacion IN ('Basico','Avanzado', NULL) )
);

CREATE TABLE Billetera_Empresa
(
    id_billetera               INT PRIMARY KEY,
    cuenta_recaudacion         VARCHAR(50),
    tasa_comision              DECIMAL(5, 2) DEFAULT 0.0295, -- Tasa por defecto que cobra yape
    limite_mensual_recaudacion DECIMAL(10, 2) DEFAULT 26750,
    -- FK
    CONSTRAINT fk_bemp_billetera
        FOREIGN KEY (id_billetera) REFERENCES Billetera_Yape (id_billetera) ON DELETE CASCADE
);

CREATE TABLE Billetera_Other_Persona
(
    id_billetera   INT PRIMARY KEY,
    id_externo     VARCHAR(50) UNIQUE NOT NULL, -- id en red externa
    nombre_externo VARCHAR(50),
    -- FK
    CONSTRAINT fk_bother_billetera
        FOREIGN KEY (id_billetera) REFERENCES Billetera_Yape (id_billetera) ON DELETE CASCADE
);

-- ===========================
-- Credencial
-- ===========================
CREATE TABLE Credencial
(
    id_billetera     INT          NOT NULL,
    id_credencial    INT          NOT NULL,
    tipo             VARCHAR(30)  NOT NULL,                  -- 'PIN','Huella','Facial','Patron'
    hash_valor       VARCHAR(255) NOT NULL,
    fecha_creacion   TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_expiracion TIMESTAMP,
    estado           VARCHAR(20)  NOT NULL DEFAULT 'Activa', -- 'Activa','Expirada','Bloqueada'
    PRIMARY KEY (id_billetera, id_credencial),
    -- FK
    CONSTRAINT fk_cred_billetera
        FOREIGN KEY (id_billetera) REFERENCES Billetera_Yape (id_billetera) ON DELETE CASCADE,
    CONSTRAINT chk_cred_estado
        CHECK (estado IN ('Activa', 'Expirada', 'Bloqueada')),
    CONSTRAINT chk_cred_tipo
        CHECK ( tipo IN ('PIN','Huella','Facial','Patron') )
);

-- ===========================
-- QR
-- ===========================
CREATE TABLE QR
(
    id_qr          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_qr      VARCHAR(100) NOT NULL,
    fecha_creacion TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    activo         BOOLEAN      NOT NULL DEFAULT TRUE
);

-- QR estático (1:N con BilleteraYape )
CREATE TABLE QR_Estatico
(
    id_qr            INT PRIMARY KEY,
    id_billetera     INT     NOT NULL,
    fecha_activacion TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    activo           BOOLEAN NOT NULL DEFAULT TRUE, -- duplicado intencional para poder indexar por billetera
    -- FK
    CONSTRAINT fk_qre_qr FOREIGN KEY (id_qr) REFERENCES QR (id_qr) ON DELETE CASCADE,
    CONSTRAINT fk_qre_billetera FOREIGN KEY (id_billetera) REFERENCES Billetera_Yape (id_billetera) ON DELETE CASCADE
);

-- QR dinámico (1:1 con TransaccionEmpresaAE)
CREATE TABLE QR_Dinamico
(
    id_qr          INT PRIMARY KEY,
    monto_fijo     DECIMAL(12, 2) NOT NULL,
    tiempo_validez INT DEFAULT 300          NOT NULL -- segundos
);

-- ===========================
-- Transacción
-- ===========================
CREATE TABLE Transaccion_Yape
(
    id_transaccion   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_hora       TIMESTAMP          NOT NULL DEFAULT CURRENT_TIMESTAMP,
    estado           VARCHAR(20)        NOT NULL, -- 'Exitosa','Pendiente','Fallida','Revertida'
    monto            DECIMAL(10, 2)     NOT NULL CHECK (monto >= 0),
    numero_operacion VARCHAR(20) UNIQUE NOT NULL,
    -- CHECK
    CONSTRAINT chk_tx_estado CHECK (estado IN ('Exitosa', 'Pendiente', 'Fallida', 'Revertida'))
);

CREATE TABLE Transaccion_Persona
(
    id_transaccion   INT PRIMARY KEY,
    codigo_seguridad VARCHAR(4),
    tipo_destino     VARCHAR(20), -- 'Yape','Plin','Tunki','Otra'
    numero_receptor  VARCHAR(9),
    nombre_receptor  VARCHAR(50),
    nombre_emisor    VARCHAR(50),
    -- FK
    CONSTRAINT fk_txp_tx FOREIGN KEY (id_transaccion) REFERENCES Transaccion_Yape (id_transaccion) ON DELETE CASCADE,
    -- CHECK
    CONSTRAINT chk_tpersona_destino CHECK ( tipo_destino IN ('Yape', 'Plin', 'Agora', 'Tunki', 'Otro', NULL) )
);

CREATE TABLE Transaccion_Servicios
(
    id_transaccion          INT PRIMARY KEY,
    codigo                  VARCHAR(20), -- código del recibo/servicio
    descripcion             VARCHAR(255),
    tipo_operacion_servicio VARCHAR(50), -- 'Agua','Luz','Telefono', etc.
    -- FK
    CONSTRAINT fk_txs_tx FOREIGN KEY (id_transaccion) REFERENCES Transaccion_Yape (id_transaccion) ON DELETE CASCADE
);

CREATE TABLE Transaccion_Empresa_AE
(
    id_transaccion     INT PRIMARY KEY,
    id_qr              INT UNIQUE,
    fecha_confirmacion TIMESTAMP,
    descripcion        VARCHAR(255),
    -- FK
    CONSTRAINT fk_txae_tx FOREIGN KEY (id_transaccion) REFERENCES Transaccion_Yape (id_transaccion) ON DELETE CASCADE,
    CONSTRAINT fk_txae_qr FOREIGN KEY (id_qr) REFERENCES QR_Dinamico (id_qr) ON DELETE SET NULL
);

-- ===========================
-- RELACIÓN TERNARIA: OPERACION YAPE
-- (TransaccionYape + Billetera Emisor + Billetera Receptor)
-- ===========================
CREATE TABLE Operacion_Yape
(
    id_transaccion        INT NOT NULL,
    id_billetera_emisor   INT NOT NULL,
    id_billetera_receptor INT NOT NULL,
    PRIMARY KEY (id_transaccion, id_billetera_emisor, id_billetera_receptor),
    -- FK
    CONSTRAINT uq_op_tx UNIQUE (id_transaccion), -- asegurar una sola tupla por transacción
    CONSTRAINT fk_op_tx FOREIGN KEY (id_transaccion) REFERENCES Transaccion_Yape (id_transaccion) ON DELETE CASCADE,
    CONSTRAINT fk_op_be FOREIGN KEY (id_billetera_emisor) REFERENCES Billetera_Yape (id_billetera) ON DELETE RESTRICT,
    CONSTRAINT fk_op_br FOREIGN KEY (id_billetera_receptor) REFERENCES Billetera_Yape (id_billetera) ON DELETE RESTRICT,
    -- CHECK
    CONSTRAINT chk_op_distintos CHECK (id_billetera_emisor <> id_billetera_receptor)
);

-- ===========================
-- Notificación
-- ===========================
CREATE TABLE Notificacion
(
    id_notificacion INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mensaje         VARCHAR(255) NOT NULL,
    fecha_emision   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    estado          VARCHAR(20)  NOT NULL DEFAULT 'Enviada', -- 'Enviada','Leida','Pendiente','Fallida'
    canal           VARCHAR(20)  NOT NULL,                   -- 'SMS','Email','App'
    CONSTRAINT chk_notif_estado CHECK (estado IN ('Enviada', 'Leida', 'Pendiente', 'Fallida')),
    CONSTRAINT chk_notif_canal CHECK (canal IN ('SMS', 'Email', 'App'))
);

CREATE TABLE Notificacion_Billetera
(
    id_notificacion INT PRIMARY KEY,
    id_billetera    INT NOT NULL,
    tipo_alerta     VARCHAR(50), -- 'Envio','Recepcion','PagoServicio','Bloqueo','LimiteSuperado'
    -- FK
    CONSTRAINT fk_nb_n FOREIGN KEY (id_notificacion) REFERENCES Notificacion (id_notificacion) ON DELETE CASCADE,
    CONSTRAINT fk_nb_b FOREIGN KEY (id_billetera) REFERENCES Billetera_Yape (id_billetera) ON DELETE CASCADE,
    -- CHECK
    CONSTRAINT chk_nb_tipo_alerta CHECK ( tipo_alerta IN ('Bloqueo','LimiteSuperado', NULL) )
);

CREATE TABLE Notificacion_Transaccion
(
    id_notificacion INT PRIMARY KEY,
    id_transaccion  INT NOT NULL,
    monto           DECIMAL(12, 2),
    resultado       VARCHAR(20),  -- 'Exitosa','Fallida' (si quieres, refleja estado de la tx)
    tipo_operacion  VARCHAR(30),  -- 'Envio','Recepcion','PagoServicio'
    -- FK
    CONSTRAINT fk_nt_n FOREIGN KEY (id_notificacion) REFERENCES Notificacion (id_notificacion) ON DELETE CASCADE,
    CONSTRAINT fk_nt_tx FOREIGN KEY (id_transaccion) REFERENCES Transaccion_Yape (id_transaccion) ON DELETE CASCADE,
    -- CHECK
    CONSTRAINT chk_nt_resultado CHECK ( resultado IN ('Exitosa', 'Fallida', NULL) ),
    CONSTRAINT chk_nt_tipo_operacion CHECK ( tipo_operacion IN ('Envio','Recepcion','PagoServicio', 'PagoQR', 'Otro', NULL) )
);

